language: objective-c
cache: 
  - bundler
  - cocoapods
before_install:
  - gem install xcpretty -N --no-ri --no-rdoc
  - gem install cocoapods --pre --quiet --no-ri --no-rdoc
  - gem install slather --no-ri --no-rdoc
  - pod setup --silent
  - pod repo update --silent
script:
  - pod lib lint Bolts.podspec
  - pod lib lint --use-libraries Bolts.podspec
  - set -o pipefail
  - xcodebuild -project Bolts.xcodeproj -sdk macosx -scheme MacBolts -configuration Debug clean test ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild -project Bolts.xcodeproj -sdk iphonesimulator -scheme Bolts -configuration Debug clean test ONLY_ACTIVE_ARCH=NO | xcpretty -c
after_success:
  - slather coverage -s
